### ISSUE TITLE
How to create the .podspec

### ISSUE THREAD

**Issue by chernandezq** [ajakka/react-native-maps-here#2]
I've created the podspec inside the Frameworks directory but I'm getting this error "[!] No podspec found for `heresdk` in `Frameworks`" Do you know how should I create the file?
![Screenshot 2023-12-26 at 2 25 24 PM](https://github.com/ajakka/react-native-maps-here/assets/5650599/1ab2143d-1100-432e-b4f9-2e3bd8b793f8)

**Comment by ajakka** [comment]
it's better to create the podspec in vscode under the ios/Frameworks folder than place your heresdk.xcframework next to it like this:

<img width="338" alt="image" src="https://github.com/ajakka/react-native-maps-here/assets/25665218/3dbcdf66-e913-4469-87ef-3fdcf130edc4">

Than do `pod install` for cocoapods to recognize it
