### ISSUE TITLE
initializeHereSDK is causing a blank map

### ISSUE THREAD

**Issue by habhabsafi** [ajakka/react-native-maps-here#6]
I am using the `Map` component, and it displays the map even without calling `MapsHereConfig.initializeHereSDK`. 

However, **the map appears blank when I attempt to initialize the SDK** within a `useEffect` hook in the container component. I have wrapped the initialization in a` try-catch` block, but no errors are thrown. I am confident in my `HERE OAuth` credentials as they work perfectly for another web application.
<img width="331" alt="Screenshot 2024-07-09 at 12 50 04 PM" src="https://github.com/ajakka/react-native-maps-here/assets/51701864/87d4b173-942d-49fa-b080-68a3cc619f36">
The documentation states that the HERE SDK should be initialized in `index.js`, but since I am working in an Expo environment, there is no main `index.js` or `app.js` file. I am open to initializing it within the component itself as I am just testing it in a small app. Regardless, the location of the initialization should not matter, correct?
PS: the documentation does not provide guidance on setting up the SDK in an Expo environment. I had to do `expo eject`  to obtain the necessary Android files for configuration.

**Comment by ajakka** [comment]
Hi @habhabsafi Initializing the SDK should not be done inside a `useEffect`. instead call it in your index.js before the `AppRegistry.registerComponent` call, like in this example https://github.com/ajakka/react-native-maps-here/blob/main/example/index.js

**Comment by habhabsafi** [comment]
Fair enough, thanks !
